FROM rust:1-slim-trixie as build

RUN apt update && \
    apt install -y build-essential pkg-config && \
    update-ca-certificates

WORKDIR /app

COPY ./src ./src
COPY ./migrations ./migrations
COPY ./Cargo.lock .
COPY ./Cargo.toml .

RUN useradd \
    --uid 10001 \
    --user-group \
    --no-create-home \
    --home-dir "/nonexistent" \
    --shell "/usr/sbin/nologin" \
    "engine"

RUN cargo build --release


FROM debian:trixie-slim

RUN apt update && \
    apt install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
USER engine:engine

COPY --from=build --chown=engine:engine /app/target/release/engine /app/engine

ENTRYPOINT ["/app/engine"]
